version: '3.8'
services:
  frontend:
    build: .
    container_name: to-do-list-frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    volumes:
      - .:/app
